Fixed valid inventory scanner field not being replaced when destroyed
Geforce132/SecurityCraft pull request #194
Opened 2020-09-02 13:11 UTC by RedstoneDubstep

In this PR I've added a method to the InventoryScannerBlock that makes it replace a valid inventory scanner field when it gets destroyed, just like it happens with lasers. I had to remove a check if the placer of the scanner is a player, please let me know if that check was of importance.

2020-09-02 13:43 UTC, bl4ckscor3 commented
The check was there for being able to safely cast the entity to a PlayerEntity, but you removed that cast so the check became unnecessary with this change. I will test this within the next days.

2020-09-03 17:58 UTC, bl4ckscor3 requested changes
This doesn't work if the configuration option to change the inventory scanner's range is increased.

2020-09-04 09:04 UTC, bl4ckscor3 requested changes
Add `- Change: Inventory Scanner Fields now keep their connection to the Inventory Scanners even when destroyed` to the changelog (between the New and Fix sections), and you're good to go. If you have a better changelog line, don't hesitate to suggest one.

2020-09-04 10:23 UTC, RedstoneDubstep commented
What about `- Change: Inventory Scanner Fields now cannot be destroyed when between two Inventory Scanners`? In my opinion the `even when destroyed` from your changelog entry suggests that they actually can be destroyed.
And can I add the `(Thanks Redstone_Dubstep!)` to the changelog line?

2020-09-04 10:42 UTC, bl4ckscor3 commented
Yes to both.

2020-09-04 11:01 UTC, bl4ckscor3 approved these changes

2020-09-04 11:01 UTC, merged