Improved Secret Sign a bit
Geforce132/SecurityCraft pull request #201
Opened 2020-09-09 12:45 UTC by RedstoneDubstep

In this PR I've looked over the Secret Sign and was able to improve some things, including
- an ability for inserting a whitelist module that allows whitelisted players to see the sign's text
- an option that allows you to set whether only the owner and whitelisted players or everyone should be able to read the sign's text 
- a check in the `onBlockActivated` methods that only allows players that can see the sign text to interact with it

2020-09-10 10:22 UTC, bl4ckscor3 commented
The server crashes with these changes. https://gist.github.com/bl4ckscor3/aa07b16e04c3e54de85e55c6d94f1577

2020-09-10 11:15 UTC, RedstoneDubstep commented
> With these changes, the server crashes on startup. Always test on a dedicated server as well. https://gist.github.com/bl4ckscor3/aa07b16e04c3e54de85e55c6d94f1577

Sorry for not testing it, but I don't know why the server would crash, as the crash report only mentions SC once in a place that hasn't even been changed. I know it's somehow related to the SecretSignTileEntity, but I wouldn't know what changed method in there would cause the game to crash.

2020-09-10 12:09 UTC, bl4ckscor3 commented
You are using client only classes (Minecraft) in SecretSignTileEntity.

2020-09-11 05:58 UTC, JoyBates commented
Considering I came up with the Secret Sign while bl4ck sat in a Discord voice channel with me for an hour to get new ideas for the mod, dOnt yOu MEsS WiTH My SECreT SiGN. 

I approve of the first change. Second defeats the purpose of having a sign be secret and third is a question mark.

2020-09-11 07:07 UTC, RedstoneDubstep commented
Hi, thanks for joining this conversation. It's always good to have a third opinion, especially if you were the one that came up with the secret sign, so please don't blame me when I also tell you my opinion now.
The thing with the custonization option is, some players just want readable, but undestroyable signs for e.g. adventure maps or server rules at spawn written on signs. One could implement a reinforced sign for that purpose, but it's the easier solution to convert secret signs to reinforced ones via an option. You're right, it defeats the purpose of a *secret* sign, but it opens new possibilities for signs where everyone can see their text, but cannot be destroyed.
And I've implemented the last thing (your question mark) on the fly because of logic. Why should one that cannot read the sign text be able to rightclick with it, possibly triggering a command that's related to the text? Furthermore, this again opens up new possibilities, especially in combination with a whitelist module, and leads to situations where only a limited amount of players can rightclick on a sign and execute a command to e.g. teleport the player to a secret location only some players should have access to. And these whitelisted players don't have to deal with the fiddly command stuff, all they have to do is rightclick a sign only they can rightclick!

2020-09-16 11:01 UTC, bl4ckscor3 requested changes
Changing the option does not update other players on the server, so the sign text is still hidden from them even if the owner changed the sign to not be secret. This is caused by two methods missing from `SecretSignTileEntity`, that weren't necessary before. If you add
```
	@Override
	public void onOptionChanged(Option<?> option)
	{
		world.notifyBlockUpdate(pos, getBlockState(), getBlockState(), 2);
	}
```

the block is marked as having changed as soon as the option changes, so the server sends an update packet to each connected client (this packet is defined in the method `getUpdatePacket()`.
Secondly, adding

```
	@Override
	public void onDataPacket(NetworkManager net, SUpdateTileEntityPacket packet)
	{
		read(getBlockState(), packet.getNbtCompound());
	}
```

makes sure, that the client can handle the received update packet. In this case, the client just reads the NBT compound it got from the packet (please put this below `getUpdatePacket()`, as the two methods belong together semantically).

Changelog:
```
- New: Secret Signs can now have a whitelist (Thanks Redstone_Dubstep!)
- New: New customization option to make the text of Secret Signs visible to everyone (Thanks Redstone_Dubstep!)
```

`- Fix: Secret Signs can be colored by anyone (Thanks Redstone_Dubstep!)`

2020-09-16 16:35 UTC, RedstoneDubstep commented on src/main/java/net/geforcemods/securitycraft/blocks/SecretWallSignBlock.java
> +		return Util.makeTranslationKey("block", this.getRegistryName()).replace("_wall", "");
Because `super.getTranslationKey()` returns `this.asItem().getTranslationKey()` in this class as defined in `WallSignBlock`, and I do not want that.

2020-09-16 16:39 UTC, RedstoneDubstep commented on src/main/resources/assets/securitycraft/lang/en_us.json
> +	"module.securitycraft.secret_sign.whitelist_module.description": "Adding a whitelist module to a Secret Sign will allow whitelisted players to see its text.",
Suggestion: the check I included does not only prevent coloring, but also other sign right click action such as executing commands. What about changing "and color it" to "and interact with it"?

2020-09-16 16:40 UTC, bl4ckscor3 commented on src/main/resources/assets/securitycraft/lang/en_us.json
> +	"module.securitycraft.secret_sign.whitelist_module.description": "Adding a whitelist module to a Secret Sign will allow whitelisted players to see its text.",
Ok.

2020-09-16 16:41 UTC, bl4ckscor3 commented on src/main/java/net/geforcemods/securitycraft/blocks/SecretWallSignBlock.java
> +		return Util.makeTranslationKey("block", this.getRegistryName()).replace("_wall", "");
But why? What is the difference?

2020-09-16 17:10 UTC, bl4ckscor3 requested changes

2020-09-16 17:10 UTC, bl4ckscor3 commented on Changelog v1.8.x.md
> +- New: New customization option to make the text of Secret Signs visible to everyone (Thanks Redstone_Dubstep!)```
There are three backticks at the end here. Please excuse this, GitHub's formatter does not see three backticks that are not on a seperate line as the end to a code block. I have edited my previous main review comment to fix it. Please check it again and verify you've done everything I noted there.

2020-09-16 17:10 UTC, bl4ckscor3 commented on src/main/resources/assets/securitycraft/lang/de_de.json
> +	"help.securitycraft.secret_sign_item.info": "Das Geheime Schild funktioniert wie das Vanilla-Schild, mit dem Unterschied, dass nur der Besitzer und gewhitelistete Spieler den Text lesen und mit ihm
```suggestion
	"help.securitycraft.secret_sign_item.info": "Das Geheime Schild funktioniert wie das Vanilla-Schild, mit dem Unterschied, dass nur der Besitzer und gewhitelistete Spieler den Text lesen und mit dem Schild interagieren können. Stelle sicher, dass keiner den Block, an dem das Schild ist, zerstören kann!",
```

People aren't interacting with the text, but with the sign. Same with the other lines.

2020-09-16 17:10 UTC, bl4ckscor3 commented on src/main/resources/assets/securitycraft/lang/en_us.json
> +	"help.securitycraft.secret_sign_item.info": "The Secret Sign works like a vanilla sign, with the slight difference that only the owner of the sign and whitelisted players can view and interact with
```suggestion
	"help.securitycraft.secret_sign_item.info": "The Secret Sign works like a vanilla sign, with the slight difference that only the owner of the sign and whitelisted players can interact with, and view the text on it. Make sure noone can break the block it's placed on!",
```
Same thing as in the German file.

2020-09-16 18:48 UTC, merged