Update fr_fr.json to 1.16
Geforce132/SecurityCraft pull request #206
Opened 2020-10-23 06:30 UTC by JoyBates

2020-10-23 10:59 UTC, bl4ckscor3 commented on src/main/resources/assets/securitycraft/lang/fr_fr.json
> +	"messages.securitycraft:sc_help": "%s: %s + %s",
There's no need for this if it's the same as in the English file.

2020-10-23 11:08 UTC, bl4ckscor3 commented on src/main/resources/assets/securitycraft/lang/fr_fr.json
> +	"item.securitycraft.secret_warped_sign_item": "Panneau secret biscornu",
Why are the items where the blocks are?

2020-10-23 11:16 UTC, bl4ckscor3 commented on src/main/resources/assets/securitycraft/lang/fr_fr.json
> -	"block.securitycraft.reinforced_lever": "Levier renforcé",
Why delete these and move them somewhere else? Just keep them where they are...

2020-10-23 11:20 UTC, bl4ckscor3 requested changes
There are some things missing here - translations that were present before but have been modified to reflect new behavior/features. Check out en_us.json at https://github.com/Geforce132/SecurityCraft/compare/7097827a1e77f672260760c87fa8dc5a2f0f1604...ecbe1688ea362c748b36662de7135fa660374100 and compare and adapt to your changes, please.

And it is **very** inconvenient if you pull request a translation for an update _after_ said update has been released. To prevent this in the future, I would suggest you join the SecurityCraft Discord server. We'll give you the Translators role, and whenever we are close to releasing an update to the mod, we're pinging the role with the new and changed translations. That way we can get them in _before_ the release.

2020-10-23 16:25 UTC, JoyBates commented
Because I did this at 1 am and pasted the same entry twice.

On Oct 23, 2020, at 6:08 AM, bl4ckscor3 <notifications@github.com> wrote:

﻿

@bl4ckscor3 commented on this pull request.

________________________________

In src/main/resources/assets/securitycraft/lang/fr_fr.json<https://github.com/Geforce132/SecurityCraft/pull/206#discussion_r510808852>:

> +     "item.securitycraft.secret_crimson_sign_item": "Panneau secret carmin",
+       "item.securitycraft.secret_warped_sign_item": "Panneau secret biscornu",


Why are the items where the blocks are?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/Geforce132/SecurityCraft/pull/206#pullrequestreview-515566624>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AIB2C6DYVZOL4RTX4QQA45TSMFP2VANCNFSM4S4EMVDQ>.

2020-10-23 16:28 UTC, JoyBates commented
I relocated them to the same position as in en_us.json, as it makes it easier to compare the files when the lines match up.

On Oct 23, 2020, at 6:16 AM, bl4ckscor3 <notifications@github.com> wrote:

﻿

@bl4ckscor3 commented on this pull request.

________________________________

In src/main/resources/assets/securitycraft/lang/fr_fr.json<https://github.com/Geforce132/SecurityCraft/pull/206#discussion_r510812456>:

> -     "block.securitycraft.reinforced_grass_path": "Chemin d'herbe renforcé",
-       "block.securitycraft.reinforced_stone_button": "Bouton en pierre renforcé",
-       "block.securitycraft.reinforced_oak_button": "Bouton en bois de chêne renforcé",
-       "block.securitycraft.reinforced_spruce_button": "Bouton en bois de sapin renforcé",
-       "block.securitycraft.reinforced_birch_button": "Bouton en bois de bouleau renforcé",
-       "block.securitycraft.reinforced_jungle_button": "Bouton en bois d'acajou renforcé",
-       "block.securitycraft.reinforced_acacia_button": "Bouton en bois d'acacia renforcé",
-       "block.securitycraft.reinforced_dark_oak_button": "Bouton en bois de chêne noir renforcé",
-       "block.securitycraft.reinforced_lever": "Levier renforcé",


Why delete these and move them somewhere else? Just keep them where they were...

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/Geforce132/SecurityCraft/pull/206#pullrequestreview-515571370>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AIB2C6DRMYFTPQVLGPODD5LSMFQY5ANCNFSM4S4EMVDQ>.

2020-10-23 16:45 UTC, bl4ckscor3 commented
You need to compare the old en_us.json file with the new en_us.json file, and then adapt the fr_fr.json file. It doesn't matter in what order the entries in fr_fr.json are as you are not comparing with that.

2020-10-23 23:15 UTC, JoyBates commented
> You need to compare the old en_us.json file with the new en_us.json file, and then adapt the fr_fr.json file. It doesn't matter in what order the entries in fr_fr.json are as you are not comparing with that.

Seems more efficient than what I’ve been doing (Thanks, Geforce XP).

2020-10-24 00:58 UTC, JoyBates commented
Okay old friend, let me know if you find more issues/suggestions.

2020-10-24 10:33 UTC, bl4ckscor3 approved these changes

2020-10-24 10:34 UTC, merged